/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import org.junit.jupiter.api.Test
import org.junit.jupiter.api.Assertions.assertNotNull

class AppTest {
//    @Test
//    fun appHasAGreeting() {
//        val classUnderTest = App("programs/helloWorld.kt")
//        assertNotNull(classUnderTest.greeting, "app should have a greeting")
//    }

    @Test
    fun toDo() {

    }
}
